### ISSUE TITLE
Removal of libressl USE flag

### ISSUE THREAD

**Issue by Bluebottle-new** [gentoo/libressl#334]
Hi

I am one of the maintainers of the [LiGurOS distribution](https://liguros.gitlab.io/), which uses Gentoo ebuilds as its base.

While restoring libressl functionality to our ebuilds, I discovered that you are currently removing the libressl USE flag and use a dummy openssl ebuild to be able to use Gentoo ebuilds, without modification. At least for the ones working with libressl.

Although I can see the advantage of being able to then use the new gentoo ebuilds, without libressl USE flag, I fail to see how that will help distros like us, which use one ebuild to cater to openssl and libressl users.

Without the libressl USE flag I currently see no way of using ebuilds from the libressl-overlay in our distribution, without either providing the user with download links, or a libressl user manually adding the libressl-overlay.

Would you have any idea how to solve this problem? So far we are just forking the corresponding ebuilds but would love to have a central repo for libressl ebuilds.

**Comment by thesamesam** [comment]
Injecting a LibreSSL eclass might be a good hack.

**Comment by CaseOf** [comment]
I am removing libressl use from the overlay because since gentoo main portage tree is afficted by the same change makes it finally almost pointless. Readding the use flag on all packages on which it was removed on main tree need a massive effort that wont be used on working on patches that will improve compatibility for packages with libressl.
I understand that it gives you difficulties to reuse the ebuilds.
What were you planning to do with an eclass?

**Comment by Bluebottle-new** [comment]
I agree that dropping the libressl USE flag does create quite an overhead. Luckily we still have a slightly older (about one month old) portage tree, from our stable release, which contains the ebuilds before the USE flag was dropped. I still need to fork all the packages but, at least, I don't need to manually recreate each ebuild.

Although we do some automatic processing of the ebuilds in our repo creation, I haven't come up with a practical solution that would allow a dynamic switching of the libraries but I am open to suggestions.
