### ISSUE TITLE
nodejs 22.4.1 fails to build

### ISSUE THREAD

**Issue by GoldsrcSource** [gentoo/libressl#565]
[build.log](https://github.com/user-attachments/files/16230880/build.log)
`../../src/quic/tlscontext.cc:12:10: fatal error: ngtcp2/ngtcp2_crypto_quictls.h: No such file or directory`
even with -system-ssl use flag.
libressl version: 3.9.2.

**Comment by GoldsrcSource** [comment]
`../../src/quic/tlscontext.cc:12:10: fatal error: ngtcp2/ngtcp2_crypto_quictls.h: No such file or directory
   12 | #include <ngtcp2/ngtcp2_crypto_quictls.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

**Comment by GoldsrcSource** [comment]
libressl version: 3.9.2.

**Comment by orbea** [comment]
This is not a LibreSSL issue and it has already be reported for the main Gentoo issue tracker (https://bugs.gentoo.org/934497), but you can get past this error by building  `net-libs/ngtcp2` with `USE=openssl`. However it may still fail later due to yet another issue unrelated to LibreSSL which I wasn't able to figure out which has also been reported. (https://bugs.gentoo.org/932534)

**Comment by GoldsrcSource** [comment]
sorry for not checking bugs.gentoo.org before reporting issue. after adding openssl flag to ngtcp2 it fails with the same error as https://bugs.gentoo.org/932534.

**Comment by BLUcybrB14de** [comment]
> > it fails with the same error as https://bugs.gentoo.org/932534.
> 
> Yea, I'm stuck in the same place...

I was able to compile nodejs with libcxx, and clang thanks to a comment from https://bugs.gentoo.org/934497. 

Removed --shared-ngtcp2 & *nghttp2, in [this ebuild.](https://codeberg.org/blucybrb14de/cybrnet-overlay/src/branch/master/net-libs/nodejs/nodejs-99999999.ebuild)
