### ISSUE TITLE
libressl ebuild should run/package c_rehash

### ISSUE THREAD

**Issue by joecool1029** [gentoo/libressl#61]
New installs building on libressl are going to have things failing all over the place (wget and curl to name a few) as this ebuild doesn't properly run c_rehash to prep the cert directory (nor does libressl include the script).

My friend hit the problem a couple nights ago on his rpi, lots of troubleshooting to see it was this.  Filing this for him.

**Comment by uriah0** [comment]
I think what happens is that app-misc/ca-certificates is supposed to run c_rehash as part of the installation process (it gets called by the update-ca-certificates script)... On new installs, if that doesn't happen, anything using SSL won't be able to find the ca certs in /etc/ssl/certs or anywhere else...

**Comment by hasufell** [comment]
https://www.happyassassin.net/2015/01/12/a-note-about-ssltls-trusted-certificate-stores-and-platforms/

**Comment by hasufell** [comment]
app-misc/ca-certificates looks like broken shit

**Comment by hasufell** [comment]
The location for the bundle is completely wrong. Openssl (and libressl) looks for it in

```
#define X509_CERT_FILE		OPENSSLDIR "/cert.pem"
```

but the update-ca-certificate script installs it into ```/etc/ssl/certs/ca-certificates.crt```. Looks like someone randomly copied debian crap into gentoo.

The simplest fix is to do
```
dosym certs/ca-certificates.crt /etc/ssl/cert.pem
```

at the end of ```multilib_src_install_all``` in the libressl ebuild, but I am rather interested in forking the app-misc/ca-certificates thing.

Also, it is completely unclear to me why we run c_rehash in pkg_postinst. If the user adds stuff there manually, he's expected to know what he is doing.

**Comment by joecool1029** [comment]
This just broke things more.

SSL certificate problem: unable to get local issuer certificate 

on everything now.

**Comment by hasufell** [comment]
reverted in 96ebccadbb6fe398f8d589dfeee478c9efece06c for now

Can you explain exactly what breaks with which library/program? "On everything now" is not precise. I use curl with polarssl so maybe this slipped my radar.

**Comment by joecool1029** [comment]
breaks git, svn, wget, pidgin, chromium, firefox to name a view.

Really anything that needs to validate certificates.  Also when you revert to the portage copy, it triggers etc-update on something like 130 files.

**Comment by hasufell** [comment]
I cannot reproduce that. Git, svn, wget, pidgin and firefox work fine here.

```
# ls /etc/ssl
apache2  cert.pem  certs  misc  nginx  openssl.cnf  private
# file /etc/ssl/cert.pem 
/etc/ssl/cert.pem: PEM certificate
# ls /etc/ssl/certs/
ca-certificates.crt
# file /etc/ssl/certs/ca-certificates.crt: symbolic link to ../cert.pem
/etc/ssl/certs/ca-certificates.crt: symbolic link to ../cert.pem
```


> Also when you revert to the portage copy, it triggers etc-update on something like 130 files.

This suggests that you are doing something weird. Probably misconfiguration. If your directories/files look like the above terminal output suggests, then it should work.

**Comment by hasufell** [comment]
Well, curl seems to be special. Afais it doesn't adhere to the openssl methods for getting the cabundle and capath, but lets people pass them during the build of curl and sets incorrect defaults.

That means the curl ebuild needs to be fixed, since the lookup for the cabundle is _completely_ disabled if you enable curl_ssl_openssl which doesn't make sense.

As for the other apps, I still cannot reproduce. Wget and git correctly look up ```/etc/ssl/cert.pem```. I double checked that.

**Comment by uriah0** [comment]
Hello,

Not sure where things are at now, but maybe in order to keep things compatible between openssl and libressl (i.e. keep how things are set up in portage with ca-certificates and openssl similar to how things are done in this overlay for the sake of easily merging this overlay into portage when it's ready), maybe the c_rehash perl script bundled with the openssl source should be included in the libressl filesdir, and copied into /usr/sbin or some other dir in PATH, so that if it needs to be called by update-ca-certificates then that script doesn't error out when it can't find c_rehash (hence fixing this issue).

The way things work in gentoo now is that every application that needs to verify an SSL ceritificate will be looking for the cert file's hash (which is a filename symlinked to the actual certificate, such as dd8e9d41.0 -> DigiCert_Global_Root_G3.pem) in /etc/ssl/certs, and when it doesn't find it, it'll spit out the error that joecool1029 is seeing, and which I was seeing in a fresh install. At least, that's what I realized when running strace on applications which errored out for me... c_rehash is the script that generates these hashes/symlinks, and in the current gentoo set up it is quite necessary.

Anyway, I hope this helps... Just my two cents.

Cheers,
uriah

**Comment by hasufell** [comment]
> The way things work in gentoo now is that every application that needs to verify an SSL ceritificate will be looking for the cert file's hash

Applications usually use openssl functions to retrieve the location of the bundle file first... and the file hash is only the second method.

Some packages like curl are special and need additional configure switches to help it. The ebuild currently has a bug (it disables the bundle detection for openssl completely which it should never do).


> maybe the c_rehash perl script bundled with the openssl source should be included in the libressl filesdir, and copied into /usr/sbin or some other dir in PATH, so that if it needs to be called by update-ca-certificates then that script doesn't error out when it can't find c_rehash (hence fixing this issue).

I think that c_rehash is a terrible method, that's why I pointed people to ```app-crypt/p11-kit```.

We can make a separate ebuild for c_rehash if you like, but I don't intend to include it in libressl, since it's not part of libressl.

**Comment by hasufell** [comment]
https://bugs.gentoo.org/show_bug.cgi?id=539260

@blueness meow

**Comment by uriah0** [comment]
Ah, I see :-) I stand corrected, then. I wonder, though, why a bunch of apps don't work for joecool1029 now...

Unless the bundle can work in all situations, your suggestion of adding c_rehash in a separate ebuild might be a good idea... Then, maybe a USE flag in libressl might make it possible to have a switch between depending on either c_rehash or app-crypt/p11-kit.

**Comment by hasufell** [comment]
We will make the dummy-openssl ebuild then RDEPEND on that c_rehash ebuild which will also fix the calls to ```/usr/sbin/update-ca-certificates``` in app-misc/ca-certificates::gentoo.

I'll still add my own version of app-misc/ca-certificates to this overlay, probably with a different name or so.

**Comment by hasufell** [comment]
> I wonder, though, why a bunch of apps don't work for joecool1029

probably a broken system

**Comment by hasufell** [comment]
So... can you verify that this works by reinstalling
```
dev-libs/openssl::libressl
app-misc/ca-certificates::gentoo
```

**Comment by uriah0** [comment]
Seems to do the trick. However, since I had manually run c_rehash I had to run etc-update on over 300 files in /etc/ssl/certs but not a big deal.

One question, though: any reason why you chose to use the shell script version of c_rehash rather than the perl version provided with the openssl source tarball?

Cheers,
uriah

**Comment by hasufell** [comment]
uhm... I just copied it from the latest openssl ebuild which has the shell version

**Comment by joecool1029** [comment]
Dunno if you noticed but libressl 2.1.4 adds a c_rehash replacement called certhash.  Did we want to drop c_rehash now and modify libressl ebuild to handle this task?

**Comment by hasufell** [comment]
> Did we want to drop c_rehash now and modify libressl ebuild to handle this task?

I am against doing rehash in pkg_postinst and I think ca-certificates ebuild is wrong and broken. Since it uses c_rehash I don't want to rewrite it to use certhash. I have already rewritten it _properly_ in the ca branch without all that pkg_postinst hackery, but people were complaining, so that's only in that branch for now.
